### ISSUE TITLE
rknn_init 直接崩溃

### ISSUE THREAD

**Issue by liushuan** [rockchip-linux/rknpu2#1]
RK3566 
Android 11 
RAM 2G
运行到rknn_init 时候直接崩溃  运行代码
int HEADDetect::LoadRKNN(const char* cpath)
{
	FILE *fp = fopen(cpath, "rb");
	if (fp == NULL) {
		printf("fopen %s fail!\n", cpath);
		return -1;
	}
	fseek(fp, 0, SEEK_END);
	int model_len = ftell(fp);
	model = malloc(model_len);
	fseek(fp, 0, SEEK_SET);
	if (model_len != fread(model, 1, model_len, fp)) {
		printf("fread %s fail!\n", cpath);
		free(model);
		return -1;
	}
	int ret = 0;
	//ret = rknn_init(&rknn_ctx, model, model_len, RKNN_FLAG_PRIOR_MEDIUM | RKNN_FLAG_COLLECT_PERF_MASK);
	ret = rknn_init(&rknn_ctx, model, model_len, RKNN_FLAG_PRIOR_HIGH, NULL);
	if (ret < 0)
	{
		printf("rknn_init fail! ret=%d\n", ret);
		// goto Error;
	}
	free(model);
	fclose(fp);
	printf("rknn_init ret=%d\n", ret);
	return ret;
}

**Comment by ChungTak** [comment]
我的Rock 3A RK3568  和你一样～啥都没做rknn_init 就崩了` ` 返回  ret=-1

**Comment by HunterRockchips** [comment]
> RK3566 Android 11 RAM 2G 运行到rknn_init 时候直接崩溃 运行代码 int HEADDetect::LoadRKNN(const char* cpath) { FILE *fp = fopen(cpath, "rb"); if (fp == NULL) { printf("fopen %s fail!\n", cpath); return -1; } fseek(fp, 0, SEEK_END); int model_len = ftell(fp); model = malloc(model_len); fseek(fp, 0, SEEK_SET); if (model_len != fread(model, 1, model_len, fp)) { printf("fread %s fail!\n", cpath); free(model); return -1; } int ret = 0; //ret = rknn_init(&rknn_ctx, model, model_len, RKNN_FLAG_PRIOR_MEDIUM | RKNN_FLAG_COLLECT_PERF_MASK); ret = rknn_init(&rknn_ctx, model, model_len, RKNN_FLAG_PRIOR_HIGH, NULL); if (ret < 0) { printf("rknn_init fail! ret=%d\n", ret); // goto Error; } free(model); fclose(fp); printf("rknn_init ret=%d\n", ret); return ret; }

有log吗

**Comment by qingqinghu1026** [comment]
> > RK3566 Android 11 RAM 2G 运行到rknn_init 时候直接崩溃 运行代码 int HEADDetect::LoadRKNN(const char* cpath) { FILE *fp = fopen(cpath, "rb"); if (fp == NULL) { printf("fopen %s fail!\n", cpath); return -1; } fseek(fp, 0, SEEK_END); int model_len = ftell(fp); model = malloc(model_len); fseek(fp, 0, SEEK_SET); if (model_len != fread(model, 1, model_len, fp)) { printf("fread %s fail!\n", cpath); free(model); return -1; } int ret = 0; //ret = rknn_init(&rknn_ctx, model, model_len, RKNN_FLAG_PRIOR_MEDIUM | RKNN_FLAG_COLLECT_PERF_MASK); ret = rknn_init(&rknn_ctx, model, model_len, RKNN_FLAG_PRIOR_HIGH, NULL); if (ret < 0) { printf("rknn_init fail! ret=%d\n", ret); // goto Error; } free(model); fclose(fp); printf("rknn_init ret=%d\n", ret); return ret; }
> 
> 有log吗

我也碰到了同样的问题，运行测试代码时没有log？需要怎么取log

**Comment by iamecong** [comment]
请问后面怎么解决了

**Comment by qingqinghu1026** [comment]
看一下转换成.rknn时平台设置是否正确？我的是因为转换.rknn的过程中错误设置成了3588（正确应为3568）
