### ISSUE TITLE
undefined symbol: wrapbuffer_virtualaddr_t

### ISSUE THREAD

**Issue by chouscode** [rockchip-linux/rknpu2#12]
Run the rknn_yolov5_demo on the RK3566, and meeting the error:
![image](https://user-images.githubusercontent.com/35787955/156739776-58b9aa18-4ea7-4b04-943d-857260088a9f.png)

I have no idea about this error, please help!!!

**Comment by CHENTian-96** [comment]
I have the same problem, have you solved it?

**Comment by chouscode** [comment]
> 
yes, delete the relevant codes about rga in your project. 
This is only a function handle for rendering and model-inference is not affected.

**Comment by analwang** [comment]
> > 
> 
> yes, delete the relevant codes about rga in your project. This is only a function handle for rendering and model-inference is not affected.

i think i meet the similar problem with running the rknn_yolov5_demo on the RK3588:
resize with RGA!
failed to open RGA:No such file or directory.
Segmentation fault (core dumped)

can you help me?

**Comment by HidingSky** [comment]
In the kernel configuration, make sure to enable MULTI_RGA and do not enable RGA or RGA2.
