### ISSUE TITLE
yolov5 demo 运行错误 kernel:[ 1150.930469] Internal error: Oops: 96000046 [#3] SMP

### ISSUE THREAD

**Issue by zh-ang-kai** [rockchip-linux/rknpu2#13]
linaro@linaro-alip: ~/rknn_yolov5_demo_Linux$ sudo ./rknn_yolov5_demo model/RK356X/yolov5s-640-640.rknn model/bus.jpg
Rga built version:274b345
post process config: box_conf_threshold = 0.50, nms_threshold = 0.60
Read model/bus.jpg ...
img width = 640, img height = 640
Loading mode...

Message from syslogd@linaro-alip at Mar  9 09:14:06 ...
 kernel:[ 1150.930469] Internal error: Oops: 96000046 [#3] SMP

Message from syslogd@linaro-alip at Mar  9 09:14:07 ...
 kernel:[ 1150.935380] Process rknn_yolov5_dem (pid: 1446, stack limit = 0x00000000aeaa45cd)

Message from syslogd@linaro-alip at Mar  9 09:14:07 ...
 kernel:[ 1151.760869] Code: a8c12027 a8c12829 a8c1302b a8c1382d (a88120c7)

**Comment by HunterRockchips** [comment]
信息不全啊？有RKNN、RKNPU的log吗

**Comment by Unlicensed-driver-ljx** [comment]
linaro@linaro-alip:~/YOLOv8_RK3588_object_detect-main/build$ sudo dmesg

Message from syslogd@linaro-alip at May 13 09:57:47 ...
 kernel:[ 1725.934352] Internal error: Oops: 9600004f [#1] SMP

Message from syslogd@linaro-alip at May 13 09:57:48 ...
 kernel:[ 1726.373468] Code: 17fffffb d5033abf b940b802 11000442 (b900b802)



^C^C


^C



Message from syslogd@linaro-alip at May 13 09:59:06 ...
 kernel:[ 1804.169070] Internal error: Oops: 96000006 [#2] SMP

Message from syslogd@linaro-alip at May 13 09:59:06 ...
 kernel:[ 1804.611759] Code: aa0203f5 a90153f3 f9400033 37000bd3 (f9400662)
^C^C
