### ISSUE TITLE
请问有计划提供OpenVX API 或 NPU算子库吗

### ISSUE THREAD

**Issue by Goose-Bomb** [rockchip-linux/rknpu2#14]
之前你们用芯原的NPU IP的时候可以用他们提供的 OpenVX 与 TIM-VX 以对接 Apache TVM 等第三方 DNN 部署框架，现在 RK35xx 系列换成瑞芯微自研 NPU 了，就只能用闭源的 RKNN 了，没办法自己扩展。请问你们未来有开发算子库与支持开放标准的计划吗？

**Comment by HunterRockchips** [comment]
目前短期内暂未有相关资源计划，后续可能会有。
