### ISSUE TITLE
3588J用这个样例推理加载rknn模型的时候报错

### ISSUE THREAD

**Issue by wyzwyzzzzz** [rockchip-linux/rknpu2#17]
报错内容提示：failed to open rknpu module,need to insmod rknpu dirver failed to open rknn device
但是在官网更新了最新的3588J的驱动之后，还是会报这个错误，所使用的demo为这个demo，所使用的模型是这个仓库里面的模型https://github.com/rockchip-linux/rknn-toolkit2/tree/master/examples/onnx/yolov5 
所使用的固件是这个网站上的ubuntu固件   
https://www.t-firefly.com/doc/download/161.html

**Comment by airockchip** [comment]
应该是内核驱动没有加载。 dmesg | grep rknpu看看有没有相关信息。
