### ISSUE TITLE
Hi, is there linux .ko modules for rk356x SoC?

### ISSUE THREAD

**Issue by TurnOffNOD** [rockchip-linux/rknpu2#19]
Hi, this repo supplies runtime. Is there linux driver, whose file extension is .ko modules for rk356x?

**Comment by DaMiBear** [comment]
Did you find them now?

**Comment by TurnOffNOD** [comment]
> Did you find them now?

No.

**Comment by TurnOffNOD** [comment]
> The npu driver has been merged into the kernel and has been open sourced and can be obtained from the kernel code.

Hi, thanks for replying.
Do you mean the driver has been merged into mainline kernel? Or it has been merged into rockchip-released kernel?
