### ISSUE TITLE
undefined reference to `rknn_init'

### ISSUE THREAD

**Issue by qq1243196045** [rockchip-linux/rknpu2#2]
代码：

int main() {
    const char *model_path = "/home/white/CLionProjects/yolo5s/model/yolox.rknn";
    const char *img_path = "/home/white/Documents/dataset/1716/VOCdevkit/VOC2007/JPEGImages/000002.jpg";
    std::cout<<model_path<<std::endl;
    rknn_context ctx;
    int ret;
    int model_len = 0;
    unsigned char *model;
    model = load_model(model_path, &model_len);
//    ret = rknn_init(&ctx,model,model_len,0);
    rknn_init(&ctx, nullptr, 0, 0);
    std::cout<<ret<<std::endl;
    std::cout << "Hello, World!" << std::endl;
    return 0;
}
报错信息：
undefined reference to `rknn_init'
collect2: error: ld returned 1 exit status

**Comment by HunterRockchips** [comment]
> 代码：
> 
> int main() { const char *model_path = "/home/white/CLionProjects/yolo5s/model/yolox.rknn"; const char *img_path = "/home/white/Documents/dataset/1716/VOCdevkit/VOC2007/JPEGImages/000002.jpg"; std::cout<<model_path<<std::endl; rknn_context ctx; int ret; int model_len = 0; unsigned char *model; model = load_model(model_path, &model_len); // ret = rknn_init(&ctx,model,model_len,0); rknn_init(&ctx, nullptr, 0, 0); std::cout<<ret<<std::endl; std::cout << "Hello, World!" << std::endl; return 0; } 报错信息： undefined reference to `rknn_init' collect2: error: ld returned 1 exit status

应该是库没链接上，建议查一下路径

**Comment by WangFengtu1996** [comment]
@qq1243196045 hello，yolox的算子在rknn中都能支持么？
