### ISSUE TITLE
rk3588_platform  rknn_run failed

### ISSUE THREAD

**Issue by wudi9932** [rockchip-linux/rknpu2#21]
model input num: 4, output num: 1
input tensors:
index=0 name=input_imgs n_dims=4 dims=[12 256 128 1] n_elems=393216 size=786432 fmt=0 type=1 qnt_type=2 fl=0 zp=0 scale=1.000000
index=1 name=desire n_dims=2 dims=[0 0 8 1] n_elems=8 size=16 fmt=0 type=1 qnt_type=2 fl=0 zp=0 scale=1.000000
index=2 name=traffic_convention n_dims=2 dims=[0 0 2 1] n_elems=2 size=4 fmt=0 type=1 qnt_type=2 fl=0 zp=0 scale=1.000000
index=3 name=initial_state n_dims=4 dims=[512 1 1 1] n_elems=512 size=1024 fmt=0 type=1 qnt_type=2 fl=0 zp=0 scale=1.000000
output tensors:
index=0 name=outputs n_dims=2 dims=[0 0 6409 1] n_elems=6409 size=12818 fmt=0 type=1 qnt_type=2 fl=0 zp=0 scale=1.000000
E RKNN: [07:24:10.076] Meet unsupported split
Aborted

**Comment by wudi9932** [comment]
所使用的模型是onnx转的，关闭了量化选项

**Comment by HunterRockchips** [comment]
从log看，split有问题，可以看看split op是否前后量化精度不一致？

**Comment by wudi9932** [comment]
问题已解决，更新了官方给的1.3.4b2版本，重新转换模型，就能运行了，但出现了返回推理结果不准确的问题，还在调试
