### ISSUE TITLE
rknpu2没有提供在模拟器上运行的接口吗

### ISSUE THREAD

**Issue by shivabohemian** [rockchip-linux/rknpu2#22]

**Comment by HunterRockchips** [comment]
这个在rknn-toolkit2工程中已经封装， rknpu2主要给调用C API做部署用的

**Comment by shivabohemian** [comment]
rknn-toolkit只有python版，rknpu2是c/c++接口，有没有考虑rknn-toolkit2也提供c/c++版本呢，这样就能统一了，开发者也便于在一套代码中同时适配npu和模拟器

**Comment by HunterRockchips** [comment]
toolkit主要用于快速上手和结果的准确性验证，实际部署主要还是在c api上
