### ISSUE TITLE
编译运行rknn_yolov5_demo的时候,提示需要librga.so.2

### ISSUE THREAD

**Issue by liyan110120999** [rockchip-linux/rknpu2#24]
./rknn_yolov5_demo model/RK356X/yolov5s-640-640.rknn model/bus.jpg
执行代码提示
./rknn_yolov5_demo: error while loading shared libraries: librga.so.2: cannot open shared object file: No such file or directory

文档中有librga.so文件的说明,请问librga.so.2这个文件如何获取?

**Comment by HunterRockchips** [comment]
应该就是librga.so，把librga.so rename成librga.so.2试一下

**Comment by liyan110120999** [comment]
测试了，不太行
我用ldd rknn_yolov5_demo命令查看了依赖，显示需要librga.so.2 这个文件，是不是gcc交叉编译的问题？
文档中推荐版本 gcc-9.3.0-x86_64_arrch64-linux-gnu，下载地址: https://github.com/rockchip-linux/gcc-buildroot-9.3.0-2020.03-x86_64_aarch64-rockchip- linux-gnu

这个链接下载不了，我下载了其他x86_64_aarch64版本

**Comment by HunterRockchips** [comment]
我问了负责rga的同事，他说是Debian里面会有要求在库后面加版本号，可以做一个软链接link到librga.so

**Comment by liyan110120999** [comment]
好的，我试一下
