### ISSUE TITLE
  Android rknn_init fail! ret=-1

### ISSUE THREAD

**Issue by qingqinghu1026** [rockchip-linux/rknpu2#25]

**Comment by qingqinghu1026** [comment]
RK3568 Android 版本测试YOLOX模型时，rknn_init报错，rknn_init fail! ret=-1
编译工具链：android-ndk-r17c-linux-x86_64
onnx转rknn：toolkit1.2.0
rknpu：rknpu2 1.2.0版本（librknnrt.so）
请问可能是什么原因造成init出错？

**Comment by HunterRockchips** [comment]
工具链可能有点问题？有完整log吗

**Comment by qingqinghu1026** [comment]
06-28 09:30:04.462 26854 26854 E RKNN    : The rknn model does not match the RKNPU hardware version!
06-28 09:30:04.463 26854 26854 E RKNN    : rknn_init, load model failed!

**Comment by HunterRockchips** [comment]
那你这个模型编出来不对啊，你编译模型设置的Target，与实际你用的板子的不一样
有区分RK3568、RK3588

**Comment by qingqinghu1026** [comment]
> 那你这个模型编出来不对啊，你编译模型设置的Target，与实际你用的板子的不一样 有区分RK3568、RK3588

好的，问题已解决，谢谢

**Comment by WangFengtu1996** [comment]
@qingqinghu1026 yolox 的所有算子能在rknn中支持么？

**Comment by qingqinghu1026** [comment]
> @qingqinghu1026 yolox 的所有算子能在rknn中支持么？

可以

**Comment by WangFengtu1996** [comment]
@qingqinghu1026  hello, 如果可以的话，可以将转换完的rknn模型分享给我么，不胜感谢！

**Comment by qingqinghu1026** [comment]
> @qingqinghu1026 yolox 的所有算子能在rknn中支持么？



> @qingqinghu1026 hello, 如果可以的话，可以将转换完的rknn模型分享给我么，不胜感谢！

你好，由于模型设计其他人成功，暂不能分享。   之前回复的有误，slice  rk是不支持的，yolox pth转onnx兼容RK需要进行conv替换slice，可以修改export_onnx.py
