### ISSUE TITLE
rknpu2工具包中只有arm架构的librknn_api.so

### ISSUE THREAD

**Issue by qq1243196045** [rockchip-linux/rknpu2#3]
我需要在x86 pc上重写数据预处理和后处理代码，但是由于没有对应的x86api,我该怎么调试自己的代码以保证正确性呢？

**Comment by HFauto** [comment]
有没有跑通yolo，效果怎么样

**Comment by HunterRockchips** [comment]
> 我需要在x86 pc上重写数据预处理和后处理代码，但是由于没有对应的x86api,我该怎么调试自己的代码以保证正确性呢？

这个不需要api吧？你只要构建自己的数据就可以了前后处理代码和api没有关系。这是代码的问题。
