### ISSUE TITLE
例程中opencv-aarch64包中不包含video-io库

### ISSUE THREAD

**Issue by llsangsang** [rockchip-linux/rknpu2#33]
想读取视频应该怎么解决

**Comment by cena001plus** [comment]
> 通过mpp框架或者自己编译一个可以读取的opencv。android可以参考 https://github.com/rockchip-linux/rknpu2/tree/master/examples/rknn_yolov5_android_apk_demo

我已经编译了opencv，吧videoio.a 放进了 example下的  opencv-linux-aarch64中的lib下面了，还是找不到这个库
