### ISSUE TITLE
rk3588_platform rknn_run failed

### ISSUE THREAD

**Issue by longnp91** [rockchip-linux/rknpu2#34]
model input num: 4, output num: 1
input tensors:
index=0 name=input_imgs n_dims=4 dims=[12 256 128 1] n_elems=393216 size=786432 fmt=0 type=1 qnt_type=2 fl=0 zp=0 scale=1.000000
index=1 name=desire n_dims=2 dims=[0 0 8 1] n_elems=8 size=16 fmt=0 type=1 qnt_type=2 fl=0 zp=0 scale=1.000000
index=2 name=traffic_convention n_dims=2 dims=[0 0 2 1] n_elems=2 size=4 fmt=0 type=1 qnt_type=2 fl=0 zp=0 scale=1.000000
index=3 name=initial_state n_dims=4 dims=[512 1 1 1] n_elems=512 size=1024 fmt=0 type=1 qnt_type=2 fl=0 zp=0 scale=1.000000
output tensors:
index=0 name=outputs n_dims=2 dims=[0 0 6409 1] n_elems=6409 size=12818 fmt=0 type=1 qnt_type=2 fl=0 zp=0 scale=1.000000
E RKNN: [07:24:10.076] Meet unsupported split
Aborted

I downloaded latest rknpu2 and rknn-toolkit2 and run on rk3588 board. And I got the above error. I saw the same issue published but still left open. And there is no fix in official release. Please help!

**Comment by airockchip** [comment]
Please update rknn toolkit2 to version 1.4.0. I tested it on this version.

   https://github.com/rockchip-linux/rknn-toolkit2
