### ISSUE TITLE
请问 RK356X 的 rknpu2 的 npu 驱动 galcore.ko 之类 哪里获取

### ISSUE THREAD

**Issue by online2311** [rockchip-linux/rknpu2#43]
请问 RK356X 的 rknpu2 的 npu 驱动 galcore.ko 之类 哪里获取。rknpu [https://github.com/rockchip-linux/rknpu/tree/master/drivers/npu_ko] 就提供相对应的驱动。

**Comment by airockchip** [comment]
RK356X/RK3588/RV1103/RV1106的npu内核驱动是开源的，直接集成到了kernel下，需要获取kernel去编译更新。

**Comment by LinoSun** [comment]
你好 想补充问下，您说的那个内核驱动是开源的，有相关链接吗，第一次弄不知道从哪下载

**Comment by bobqianic** [comment]
我觉得这里写的比较详细:
https://github.com/ophub/kernel/blob/main/README.cn.md
你可以看到在driver目录里有rknpu的文件夹，一般的kernel里面并没有。
至于他怎么获取到新版本的rknpu的驱动源码我并不清楚，可能需要发邮件问rockchip？@airockchip
![image](https://github.com/rockchip-linux/rknpu2/assets/129547291/bdf30cca-94e6-4630-b285-35d33bf18582)


rockchip之前开源过kernel，但是之后不维护了(https://github.com/rockchip-linux/kernel)
