### ISSUE TITLE
在rknn-toolkit2 使用rk3588推理结果正确 用c++模型推理结果不正确

### ISSUE THREAD

**Issue by tomjeans** [rockchip-linux/rknpu2#44]
模型是picodet 未量化
![微信截图_20221021165622](https://user-images.githubusercontent.com/37204571/197156341-59718908-4a1b-49f4-a2bf-a5f131091c63.png)
![微信截图_20221021165725](https://user-images.githubusercontent.com/37204571/197156559-968124eb-0a84-46ef-8832-8deadd8045ac.png)
![微信截图_20221021165751](https://user-images.githubusercontent.com/37204571/197156584-c170811c-af4b-4ce1-9f25-5bbbeebf1556.png)
是这里设置的问题吗？前处理跟python 一致
![image](https://user-images.githubusercontent.com/37204571/197156868-eb990add-1402-4c9e-bd14-81ff4aa13e10.png)
![image](https://user-images.githubusercontent.com/37204571/197156953-cd04b081-13d2-44c0-841b-a565f7fae987.png)

**Comment by airockchip** [comment]
1. std_values确定是0/1？
2. c代码里面type需要设置成RKNN_TENSOR_UINT8
3. 其他地方看起来没有问题

**Comment by tomjeans** [comment]
@airockchip 谢谢 就是type的问题 设置成RKNN_TENSOR_UINT8结果正常

**Comment by haha911** [comment]
@tomjeans 麻烦问下，你的模型yolov5 用的哪个版本？V6.1可以吗？
