### ISSUE TITLE
官方yolov7使用rknn-toolkit2导出模型后，使用rknn c API测试失败

### ISSUE THREAD

**Issue by Uhao-P** [rockchip-linux/rknpu2#46]
## 1.官方yolov7使用rknn-toolkit2导出模型时，QUANTIZE_ON = False。
（QUANTIZE_ON = True时输出的box坐标有值但所有框和类别的置信度都为0）
![image](https://user-images.githubusercontent.com/42427430/198012043-4401e489-59e7-49b0-aea9-78f3d8224a5f.png)
## 2.使用未量化rknn模型在板子上进行推理，打印模型的输入输出信息如下：
![image](https://user-images.githubusercontent.com/42427430/198012939-3c58756e-f4c3-444a-8d26-aa34ec42afdf.png)
## 3.根据官方文档中描述，可得知可以给输入设置uint8 / float16 / float32数据类型
<img width="646" alt="image" src="https://user-images.githubusercontent.com/42427430/198013275-047db21e-69b0-4b99-bc69-d95b9326da0b.png">

## 4.进行float32/uint8两种测试，测试输入数据

```python
//输入格式为uint8
cv::Mat orig_img = cv::imread(image_name, 1);
cv::Mat img;
cv::cvtColor(orig_img, img, cv::COLOR_BGR2RGB);

inputs[0].type = RKNN_TENSOR_UINT8;
inputs[0].size = width * height * channel;
inputs[0].buf = (void*)img.data;

//输入格式为float32
cv::Mat orig_img = cv::imread(image_name, 1);
cv::Mat img;
cv::cvtColor(orig_img, img, cv::COLOR_BGR2RGB);
img.convertTo(img, CV_32F, 1.0 / 255, 0);

inputs[0].type = RKNN_TENSOR_FLOAT32;
inputs[0].size = width * height * channel * 4;
inputs[0].buf = (void*)img.data;
```

## 5.上述两种不同的输入数据格式都会在`ret = rknn_run(ctx, NULL)`时报同一个错误
![image](https://user-images.githubusercontent.com/42427430/198015041-a780a24c-f5b2-4d5d-9a2a-fe9fca49c36b.png)

**Comment by eRaul** [comment]
inputs里的type/size是根据你的buf去填的，你现在这个都是img图像，type都应该填uint8。你的图像实际的宽度和高度跟你填的width/height对得上吗？

**Comment by Uhao-P** [comment]
1.img的w/h与input_shape相同的
2.inputs里的type/size是根据我的buf去填的，我尝试了uint8和float32两种方式（img.convertTo(img, CV_32F, 1.0 / 255, 0)归一化并转为float32），都会报错

**Comment by Uhao-P** [comment]
如果是上述第4步出的问题，是否可以提供一个正确的数据处理与input设置的code

**Comment by eRaul** [comment]
> 如果是上述第4步出的问题，是否可以提供一个正确的数据处理与input设置的code

如果size都是正确的，那应该没问题才对呀。你现在format填的是什么？

**Comment by eRaul** [comment]
完整的inputs设置发出来看看

**Comment by eRaul** [comment]
还有，你用的是普通API，还是零拷贝API?

**Comment by Uhao-P** [comment]
我使用的是普通api
```python
cv::Mat orig_img = cv::imread(image_name, 1);
cv::Mat img;
cv::cvtColor(orig_img, img, cv::COLOR_BGR2RGB);

rknn_input inputs[1];  
memset(inputs, 0, sizeof(inputs));
inputs[0].index        = 0;
inputs[0].type         = RKNN_TENSOR_UINT8;
inputs[0].size         = width * height * channel;
inputs[0].fmt          = RKNN_TENSOR_NHWC;
inputs[0].pass_through = 0;
inputs[0].buf = (void*)img.data;


rknn_inputs_set(ctx, io_num.n_input, inputs);
ret = rknn_run(ctx, NULL);
```

**Comment by Uhao-P** [comment]
上面发的是输入为uint8，以下是为float32
```python
//输入格式为float32
cv::Mat orig_img = cv::imread(image_name, 1);
cv::Mat img;
cv::cvtColor(orig_img, img, cv::COLOR_BGR2RGB);
img.convertTo(img, CV_32F, 1.0 / 255, 0);

rknn_input inputs[1];  
memset(inputs, 0, sizeof(inputs));
inputs[0].index        = 0;
inputs[0].type         = RKNN_TENSOR_FLOAT32;
inputs[0].size         = width * height * channel * 4;
inputs[0].fmt          = RKNN_TENSOR_NHWC;
inputs[0].pass_through = 0;
inputs[0].buf = (void*)img.data;


rknn_inputs_set(ctx, io_num.n_input, inputs);
ret = rknn_run(ctx, NULL);
```

**Comment by eRaul** [comment]
这个设置看起来是没有问题的。你直接printf看下buf里是不是确实有size指定数量的数据，如果数据确实是正确的，那应该是NPU实现哪里有问题。需要提供复现的RKNN模型给我们分析下。

**Comment by Uhao-P** [comment]
好的 我先验证一下buf与seize是否一致，若一致的话我把我onnx模型与onnx2rknn的转换脚本发出来

**Comment by eRaul** [comment]
> 

yolov7的模型我们也跑过，验证是没问题的。回头我让我同事整理下他的c代码，给你参考下。

**Comment by zen-xingle** [comment]
Q:（QUANTIZE_ON = True时输出的box坐标有值但所有框和类别的置信度都为0）
A: 这个问题可以参考这里，是一模一样的问题，https://github.com/rockchip-linux/rknn-toolkit/issues/93

**Comment by Uhao-P** [comment]
@zen-xingle 明白了，我的确把坐标与置信度合成到一个输出里面，我试着保留原始的特征输出再去做量化与模型转化

**Comment by Uhao-P** [comment]
@eRaul 有参考的话就太棒了 多谢多谢

**Comment by zen-xingle** [comment]
输出结构改成和 yolov5 一样的结构，C demo 直接套用 yolov5 的 C demo代码就可以跑了。 yolov5/yolov7 的前后处理逻辑是完全一致的，默认anchor不一样这个需要注意一下。

yolov5的修改可以参考这里 https://github.com/airockchip/rknn_model_zoo/tree/main/models/vision/object_detection/yolov5-pytorch

**Comment by Uhao-P** [comment]
@zen-xingle 了解。其实v7与v5的后处理还是有差别的，我当时想更省事就在导出onnx模型时把输出的特征图给统一处理了，这才导致了后续的问题。

**Comment by Uhao-P** [comment]
```python
x[0] = x[0].permute(0, 1, 4, 2, 3).reshape(1, 255, 80, 80)
x[1] = x[1].permute(0, 1, 4, 2, 3).reshape(1, 255, 40, 40)
x[2] = x[2].permute(0, 1, 4, 2, 3).reshape(1, 255, 20, 20)
```
我按照以上的操作对yolov7的输出进行修改后，在rknn-toolkits2 python api正常转换并预测成功（已经更换对应的anchor），但是到c api这边报错，并且输出的结果也是不正确的（已经更换对应的anchor）
![image](https://user-images.githubusercontent.com/42427430/198821846-8cce5ae4-bd8f-4a43-b96b-cf780e88e25d.png)

**Comment by Uhao-P** [comment]
```python
x[0] = x[0].transpose(2, 4).transpose(3, 4).reshape(1, 255, 80, 80)
x[1] = x[1].transpose(2, 4).transpose(3, 4).reshape(1, 255, 40, 40)
x[2] = x[2].transpose(2, 4).transpose(3, 4).reshape(1, 255, 20, 20)
```
我又尝试了这样的方法改变输出，与上面的结果一样，依旧是rknn-toolkits2 python api成功c api失败
@zen-xingle

**Comment by Uhao-P** [comment]
在rknn-toolkits2 python api正常转换并预测成功（已经更换对应的anchor），但是到c api这边报错，并且输出的结果也是不正确的（已经更换对应的anchor），并且我拿rknn-toolkits2中提供的yolov5s.onnx转rknn也会出现类似的错误。
![image](https://user-images.githubusercontent.com/42427430/198843240-67126a56-b89a-4590-b2d3-52009480541e.png)

@eRaul @zen-xingle

**Comment by Uhao-P** [comment]
![image](https://user-images.githubusercontent.com/42427430/198843310-b056189c-b0e9-4374-8b2c-b9910bf46e03.png)
这是我使用的onnx2rknn主要code

**Comment by BboyHanat** [comment]
yolov8 我使用混合量化，板端 python 接口预测正常， c++ 接口预测有问题。请问有遇到这个情况的吗

**Comment by falling-sno** [comment]
> @eRaul 有参考的话就太棒了 多谢多谢

请问有如何修改yolov7官方导出onnx的参考吗
