### ISSUE TITLE
rk3568使用rknn_yolov5_android_apk_demo报错rga2    : req argument is inval

### ISSUE THREAD

**Issue by sunyb12** [rockchip-linux/rknpu2#47]
10-25 06:32:13.744     0     0 W         : invalid destination resolution act_w = 120, act_h = 0
10-25 06:32:13.744     0     0 E rga2    : req argument is inval
10-25 06:32:13.639  2312  2312 E rkyolo4j: colorConvert failed. Ret: Fatal error: Failed to call RockChipRga interface, query log to find the cause of failure.
10-25 06:32:13.767     0     0 W         : invalid destination resolution act_w = 120, act_h = 46080
10-25 06:32:13.767     0     0 E rga2    : req argument is inval
10-25 06:32:13.650  2312  2367 E rkyolo4j: run_yolo: resize image with rga failed: Fatal error: Failed to call RockChipRga interface, query log to find the cause of failure.
10-25 06:32:13.777     0     0 W         : invalid destination resolution act_w = 120, act_h = 0
10-25 06:32:13.777     0     0 E rga2    : req argument is inval
10-25 06:32:13.675  2312  2312 E rkyolo4j: colorConvert failed. Ret: Fatal error: Failed to call RockChipRga interface, query log to find the cause of failure.
10-25 06:32:13.802     0     0 W         : invalid destination resolution act_w = 120, act_h = 46080
10-25 06:32:13.802     0     0 E rga2    : req argument is inval
10-25 06:32:13.685  2312  2367 E rkyolo4j: run_yolo: resize image with rga failed: Fatal error: Failed to call RockChipRga interface, query log to find the cause of failure.
10-25 06:32:13.812     0     0 W         : invalid destination resolution act_w = 120, act_h = 0
10-25 06:32:13.812     0     0 E rga2    : req argument is inval
10-25 06:32:13.711  2312  2312 E rkyolo4j: colorConvert failed. Ret: Fatal error: Failed to call RockChipRga interface, query log to find the cause of failure.
10-25 06:32:13.838     0     0 W         : invalid destination resolution act_w = 120, act_h = 46080
10-25 06:32:13.838     0     0 E rga2    : req argument is inval

**Comment by sunyb12** [comment]
需要更新librga和rga driver

**Comment by LLhon** [comment]
> 需要更新librga和rga driver

我也遇到了相同的问题，请问 rga driver 怎么更新呢，是跟系统固件有关？

**Comment by sunyb12** [comment]
可以找rk的要更新包，然后编译源码，烧录镜像


| |
m13077364198_1
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | Hehong ***@***.***> |
| 发送日期 | 2022年12月13日 17:24 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
State ***@***.***> |
| 主题 | Re: [rockchip-linux/rknpu2] rk3568使用rknn_yolov5_android_apk_demo报错rga2 : req argument is inval (Issue #47) |

需要更新librga和rga driver

我也遇到了相同的问题，请问 rga driver 怎么更新呢，是跟系统固件有关？

**Comment by analwang** [comment]
> 需要更新librga和rga driver

what about this:
resize with RGA!
failed to open RGA:No such file or directory.
Segmentation fault (core dumped)

i have no idea can you help me?
