### ISSUE TITLE
Please update to 1.1.0

### ISSUE THREAD

**Issue by changtimwu** [rockchip-linux/rknpu2#5]
The RKNN runtime in this repo is still in version 1.0.0.  It can't load model files generated by current `rknn-toolkit2`, which is 1.1.0.

I saw `rknpu2` version 1.1.0 is actually available in other places.  e.g. https://gitee.com/caesar-wang/rknpu2

Please keep this repo up-to-date.  Thank you.

**Comment by HunterRockchips** [comment]
Thanks, version had updated.
