### ISSUE TITLE
rknpu1.4.0  出现错误  E RKNN: [14:57:51.577] failed to submit!,

### ISSUE THREAD

**Issue by Grifcc** [rockchip-linux/rknpu2#59]
E RKNN: [14:57:51.577] failed to submit!, op id: 1, op name: Conv:Conv_0, flags: 0x5, task start: 0, task number: 22, run task counter: 0, int status: 0
在RK3588平台上，使用toolkits2  1.4.0正常导出模型，但无法使用，出现错误

**Comment by eecn** [comment]
请问您是怎么解决这个问题的呢，我也遇到类似的问题。
E RKNN: [20:14:20.228] failed to submit!, op id: 181, op name: OutputOperator:381, flags: 0x5, task start: 438, task number: 8, run task counter: 1, int status: 0

**Comment by SunAriesCN** [comment]
请问这个问题如何解决？
