### ISSUE TITLE
./build-android.sh What caused the error?

### ISSUE THREAD

**Issue by LMR2018** [rockchip-linux/rknpu2#6]
./build-android.sh
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/Desktop/rknpu2-master/examples/rknn_ssd_demo/build/build_android_v8a
[ 33%] Linking CXX executable rknn_ssd_demo
/opt/tools/rk/android-ndk-r17//toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld:/home/ubuntu/Desktop/rknpu2-master/examples/rknn_ssd_demo/../../Android/librknn_api/arm64-v8a/librknn_api.so: file format not recognized; treating as linker script
/opt/tools/rk/android-ndk-r17//toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld:/home/ubuntu/Desktop/rknpu2-master/examples/rknn_ssd_demo/../../Android/librknn_api/arm64-v8a/librknn_api.so:1: syntax error
collect2: error: ld returned 1 exit status
CMakeFiles/rknn_ssd_demo.dir/build.make:158: recipe for target 'rknn_ssd_demo' failed
make[2]: *** [rknn_ssd_demo] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/rknn_ssd_demo.dir/all' failed
make[1]: *** [CMakeFiles/rknn_ssd_demo.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by airockchip** [comment]
It should be that the librknn_api.so file is corrupt, it is actually linked to librknnrt.so. Please redo the link.
