### ISSUE TITLE
Invalid RKNN format. rknn_query, load_model failed

### ISSUE THREAD

**Issue by AIGirl10** [rockchip-linux/rknpu2#7]
We tried to inference ssd_mobilenet _v1 model with C++ inference on Rk3566 board. But got this error

```sh
Loading model ...
rknn_init ...
I RKNN: set log level to 0
E RKNN: Invalid RKNN format
E RKNN: rknn_query, load_model failed
rknn_init fail! ret=-1
```

Tried to search the error code it said its Model Execution error, but not able to understand why its not working, because same model worked with python inference on ubuntu 16.04.

**Comment by airockchip** [comment]
Please use the lastest rknn toolkit2 and rknpu2. If there is a problem, please reopen the issue
