### ISSUE TITLE
How to install it you losers??????

### ISSUE THREAD

**Issue by easy-and-simple** [rockchip-linux/rknpu2#75]
There is no any instructions how to install it and make it working
In doc folder have some useless start guide that says : The installation is successful if the import of RKNN module doesn't fail
And what to do if it fails you stupid losers???????????????????

when I run test.py in rknn_toolkit_lite2\examples\inference_with_lite it fails with error on line 4 that says it cant import rknnlite

**Comment by easy-and-simple** [comment]
Now gives me error can't insmod rknn driver
What is this install that doesn't install anything?????

**Comment by easy-and-simple** [comment]
losers your real time library is not working

`rock@rock-3a:~/rknn-toolkit2/rknn_toolkit_lite2/examples/inference_with_lite$ python3 test.py
--> Load RKNN model
done
--> Init runtime environment
E RKNN: [11:06:04.233] failed to open rknpu module, need to insmod rknpu dirver!
E RKNN: [11:06:04.233] failed to open rknn device!
E Catch exception when init runtime!
E Traceback (most recent call last):
File "/home/rock/.local/lib/python3.9/site-packages/rknnlite/api/rknn_lite.py", line 148, in init_runtime
self.rknn_runtime.build_graph(self.rknn_data, self.load_model_in_npu)
File "rknnlite/api/rknn_runtime.py", line 840, in rknnlite.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_FAIL

**Comment by easy-and-simple** [comment]
I resolved the issue in spite of you useless losers

rock@rock-3a:~/rknn-toolkit2/rknn_toolkit_lite2/examples/inference_with_lite$ python3 test.py
--> Load RKNN model
done
--> Init runtime environment
I RKNN: [09:45:36.045] RKNN Runtime Information: librknnrt version: 1.4.0 (a10f100eb@2022-09-09T09:07:14)
I RKNN: [09:45:36.045] RKNN Driver Information: version: 0.4.2
I RKNN: [09:45:36.046] RKNN Model Information: version: 1, toolkit version: 1.4.0-c15f5e0b(compiler version: 1.4.0 (c73777b51@2022-09-05T12:06:01)), target: RKNPU lite, target platform: rk3568, framework name: PyTorch, framework layout: NCHW
done
--> Running model
resnet18
-----TOP 5-----
[812]: 0.9996696710586548
[404]: 0.0002492684288881719
[657]: 1.632158637221437e-05
[833]: 1.0159346857108176e-05
[466 895]: 9.02384545042878e-06

done
rock@rock-3a:~/rknn-toolkit2/rknn_toolkit_lite2/examples/inference_with_lite$

**Comment by hamzanaeemcowlar** [comment]
@easy-and-simple  can you please tell me how you solved it?

Thanks in advance
