### ISSUE TITLE
Any plan to have a python binding for rknn runtime API?

### ISSUE THREAD

**Issue by changtimwu** [rockchip-linux/rknpu2#8]
I think RK3566/RK3568 is more than capable of running python.  It would be great if this platform can provide the access to all resources likes camera, display, and NPU all in python. 
The works to do are pretty much wrapping the C APIs defined below into python.  
https://github.com/rockchip-linux/rknpu2/blob/master/Linux/librknn_api/include/rknn_api.h

**Comment by goloskokovic** [comment]
https://github.com/rockchip-linux/rknn-toolkit2/blob/master/rknn-toolkit-lite2-v1.2.0/examples/inference_with_lite/test.py#L71
