### ISSUE TITLE
NPU Computation Latency Is Fluctuating

### ISSUE THREAD

**Issue by msukmoon** [rockchip-linux/rknpu2#87]
Hello!

I've been playing with [rknn_api_demo](https://github.com/rockchip-linux/rknpu2/tree/v1.4.0/examples/rknn_api_demo) with the [mobilenet_v1](https://github.com/rockchip-linux/rknpu2/blob/v1.4.0/examples/rknn_api_demo/model/RK3588/mobilenet_v1.rknn) model on RK3588S.

I'm currently measuring the latency of [`rknn_run()`](https://github.com/rockchip-linux/rknpu2/blob/v1.4.0/examples/rknn_api_demo/src/rknn_create_mem_demo.cpp#LL311C25-L311C44) with the PMU cycle counter register ([`PMCCNTR_EL0`](https://developer.arm.com/documentation/ddi0601/2023-03/AArch64-Registers/PMCCNTR-EL0--Performance-Monitors-Cycle-Count-Register?lang=en)) instead of using the default [`gettimeofday(2)`](https://github.com/rockchip-linux/rknpu2/blob/v1.4.0/examples/rknn_api_demo/src/rknn_create_mem_demo.cpp#L37), and I'm seeing that the computation latency is heavily fluctuating. DVFS was disabled, and only a single core was enabled.

Does anyone happen to know if there are any hardware features that are causing this?

Thanks! :-)

**Comment by serwansj** [comment]
hi @msukmoon, did you figure out what caused the fluctuations? i am currently experiencing similar issues
